export const mockIncidentReports = [
    {
        id: 1,
        category: "Crime-Related Incidents",
        subCategory: "Theft/Burglary",
        date: "2023-06-01",
        time: "14:30",
        location: "123 Main St",
        description: "Laptop stolen from parked car",
        reporterName: "John Doe",
        reporterContact: "john@example.com",
        status: "New",
    },
    {
        id: 2,
        category: "Community Disturbances",
        subCategory: "Noise Complaints",
        date: "2023-06-02",
        time: "22:00",
        location: "456 Elm St",
        description: "Loud party past midnight",
        reporterName: "Jane Smith",
        reporterContact: "555-1234",
        status: "In Progress",
    },
    {
        id: 3,
        category: "Environmental & Health Concerns",
        subCategory: "Garbage Dumping",
        date: "2023-06-03",
        time: "09:15",
        location: "789 Oak Ave",
        description: "Illegal dumping in vacant lot",
        reporterName: "Bob Johnson",
        reporterContact: "bob@example.com",
        status: "Resolved",
    },
    // Add more mock data as needed
];
